import type { Challenge } from './types'

export const CHALLENGES: Challenge[] = [
  {
    id: 'url-shortener',
    title: 'URL Shortener',
    difficulty: 'Beginner',
    tagline: 'Turn long links into short ones and redirect fast.',
    scale: ['10M URLs', '100M redirects/day'],
    problem:
      'Marketing teams paste long links and get a short one back. Every click on a short link must redirect in milliseconds, and links must never break.',
    functional: ['Create short URLs', 'Redirect users', 'High read traffic', 'Low latency', 'Durable storage'],
    nonFunctional: [
      { label: 'Latency', target: 'Redirects under 50 ms' },
      { label: 'Availability', target: '99.9%, redirects must keep working' },
      { label: 'Durability', target: 'No link is ever lost' },
      { label: 'Read/write ratio', target: '~100 redirects per new link' },
    ],
    constraints: [
      { label: 'Traffic', value: '~1,200 redirects/s average, 5× at peaks' },
      { label: 'Data size', value: '10M links ≈ a few GB' },
      { label: 'Budget', value: 'Lean: a small team runs it' },
    ],
    criteria: [
      'Read path latency',
      'Caching hot links',
      'Durable storage',
      'Redundancy on the redirect path',
      'Abuse protection',
      'Cost for the scale',
    ],
    profile: {
      scale: 2,
      readHeavy: true,
      writeHeavy: false,
      global: false,
      media: false,
      asyncWork: false,
      realtime: false,
      strongConsistency: false,
      search: false,
      auth: false,
      analytics: false,
      rateLimiting: true,
      budget: 'lean',
    },
    services: [
      { name: 'Shortener Service', keywords: ['short', 'link', 'url'] },
      { name: 'Redirect Service', keywords: ['redirect'] },
    ],
    dependencies: [],
  },
  {
    id: 'video-platform',
    title: 'Video Learning Platform',
    difficulty: 'Advanced',
    tagline: 'Stream courses to learners around the world.',
    scale: ['5M users', '500K daily active users'],
    problem:
      'Instructors upload course videos; learners anywhere in the world stream them, track progress and pick up where they left off. Video bandwidth dwarfs everything else.',
    functional: ['Video delivery', 'Course catalog', 'Authentication', 'Progress tracking', 'Analytics', 'Global users'],
    nonFunctional: [
      { label: 'Latency', target: 'Video starts in under 2 s worldwide' },
      { label: 'Availability', target: '99.95% for playback' },
      { label: 'Scalability', target: 'Evening peaks of 5× average' },
      { label: 'Durability', target: 'Uploaded videos are never lost' },
    ],
    constraints: [
      { label: 'Global users', value: 'North America, Europe, Asia' },
      { label: 'Data size', value: 'Hundreds of TB of video' },
      { label: 'Budget', value: 'Moderate: bandwidth is the main cost' },
    ],
    criteria: ['Global delivery', 'Storage', 'CDN', 'Scalability', 'Metadata access', 'Async processing', 'Analytics'],
    profile: {
      scale: 3,
      readHeavy: true,
      writeHeavy: false,
      global: true,
      media: true,
      asyncWork: true,
      realtime: false,
      strongConsistency: false,
      search: true,
      auth: true,
      analytics: true,
      rateLimiting: false,
      budget: 'moderate',
    },
    services: [
      { name: 'Catalog Service', keywords: ['catalog', 'course'] },
      { name: 'Video Service', keywords: ['video', 'media', 'stream'] },
      { name: 'Progress Service', keywords: ['progress'] },
      { name: 'Transcoding Worker', keywords: ['transcod', 'encod'] },
    ],
    dependencies: [],
  },
  {
    id: 'notification-platform',
    title: 'Notification Platform',
    difficulty: 'Intermediate',
    tagline: 'Deliver email, SMS and push at scale, reliably.',
    scale: ['50M notifications/day'],
    problem:
      'Product teams call one API to notify users by email, SMS or push. Providers are slow and sometimes fail, so delivery must be retried without hammering them, and every message tracked.',
    functional: ['Email', 'SMS', 'Push notifications', 'Retry failed deliveries', 'Rate limiting', 'Delivery tracking'],
    nonFunctional: [
      { label: 'Reliability', target: 'At-least-once delivery' },
      { label: 'Throughput', target: '~600/s average, 10× bursts' },
      { label: 'Latency', target: 'API accepts in under 100 ms' },
      { label: 'Consistency', target: 'Delivery status eventually correct' },
    ],
    constraints: [
      { label: 'Providers', value: 'Third-party email/SMS/push with rate limits' },
      { label: 'Traffic', value: 'Bursty: campaigns send millions at once' },
      { label: 'Budget', value: 'Moderate' },
    ],
    criteria: [
      'Asynchronous delivery',
      'Retries and back-pressure',
      'Rate limiting',
      'Delivery tracking storage',
      'Burst handling',
      'Observability',
    ],
    profile: {
      scale: 2,
      readHeavy: false,
      writeHeavy: true,
      global: false,
      media: false,
      asyncWork: true,
      realtime: false,
      strongConsistency: false,
      search: false,
      auth: false,
      analytics: false,
      rateLimiting: true,
      budget: 'moderate',
    },
    services: [
      { name: 'Notification API', keywords: ['notification', 'notify', 'api'] },
      { name: 'Email Worker', keywords: ['email'] },
      { name: 'SMS Worker', keywords: ['sms'] },
      { name: 'Push Worker', keywords: ['push'] },
      { name: 'Tracking Service', keywords: ['track', 'status'] },
    ],
    dependencies: [],
  },
  {
    id: 'realtime-chat',
    title: 'Real-Time Chat',
    difficulty: 'Advanced',
    tagline: 'Messages that arrive instantly, for millions at once.',
    scale: ['10M users', '1M concurrent connections'],
    problem:
      'Users chat one-to-one and in groups, see who is online and whether messages were delivered. A million devices hold an open connection at any moment.',
    functional: ['One-to-one chat', 'Group chat', 'Message history', 'Presence', 'Delivery status'],
    nonFunctional: [
      { label: 'Latency', target: 'Messages delivered in under 200 ms' },
      { label: 'Availability', target: '99.99%' },
      { label: 'Scalability', target: '1M concurrent connections' },
      { label: 'Ordering', target: 'Messages in order per conversation' },
    ],
    constraints: [
      { label: 'Connections', value: 'Long-lived WebSockets' },
      { label: 'Data size', value: 'Billions of messages kept for history' },
      { label: 'Budget', value: 'Generous' },
    ],
    criteria: [
      'Persistent connections',
      'Message fan-out',
      'Presence storage',
      'Write-heavy history store',
      'Horizontal scaling',
      'No single points of failure',
    ],
    profile: {
      scale: 3,
      readHeavy: false,
      writeHeavy: true,
      global: true,
      media: false,
      asyncWork: true,
      realtime: true,
      strongConsistency: false,
      search: false,
      auth: true,
      analytics: false,
      rateLimiting: true,
      budget: 'generous',
    },
    services: [
      { name: 'Chat Gateway', keywords: ['chat', 'connection', 'socket'] },
      { name: 'Message Service', keywords: ['message'] },
      { name: 'Presence Service', keywords: ['presence'] },
      { name: 'Group Service', keywords: ['group'] },
    ],
    dependencies: [
      { when: ['group'], requires: ['message'], message: 'Group Service needs a Message Service to deliver group messages.' },
    ],
  },
  {
    id: 'ecommerce',
    title: 'E-Commerce Platform',
    difficulty: 'Advanced',
    tagline: 'Catalog, cart and checkout that never double-charge.',
    scale: ['10M users', '100K orders/day'],
    problem:
      'Shoppers browse and search a large catalog, fill a cart and check out. Browsing is read-heavy and spiky; checkout must charge exactly once and never oversell stock.',
    functional: ['Product catalog', 'Search', 'Cart', 'Checkout', 'Payments', 'Inventory', 'Order tracking'],
    nonFunctional: [
      { label: 'Consistency', target: 'Payments and stock strongly consistent' },
      { label: 'Latency', target: 'Product pages under 300 ms' },
      { label: 'Availability', target: '99.95%, checkout above all' },
      { label: 'Scalability', target: 'Sale days at 10× traffic' },
    ],
    constraints: [
      { label: 'Traffic', value: '100:1 browse to buy' },
      { label: 'Data size', value: 'Millions of products' },
      { label: 'Budget', value: 'Moderate' },
    ],
    criteria: [
      'Read scaling for the catalog',
      'Search',
      'Transactional checkout',
      'Service boundaries',
      'Async order fulfilment',
      'Single points of failure',
    ],
    profile: {
      scale: 2,
      readHeavy: true,
      writeHeavy: false,
      global: false,
      media: false,
      asyncWork: true,
      realtime: false,
      strongConsistency: true,
      search: true,
      auth: true,
      analytics: false,
      rateLimiting: false,
      budget: 'moderate',
    },
    services: [
      { name: 'Catalog Service', keywords: ['catalog', 'product'] },
      { name: 'Cart Service', keywords: ['cart'] },
      { name: 'Checkout Service', keywords: ['checkout'] },
      { name: 'Payment Service', keywords: ['payment'] },
      { name: 'Inventory Service', keywords: ['inventory', 'stock'] },
      { name: 'Order Service', keywords: ['order'] },
    ],
    dependencies: [
      { when: ['checkout'], requires: ['payment'], message: 'Checkout Service requires Payment Service.' },
      {
        when: ['checkout'],
        requires: ['inventory', 'stock'],
        message: 'Checkout Service requires Inventory Service to reserve stock.',
      },
    ],
  },
]

export function getChallenge(id: string | null | undefined): Challenge | undefined {
  return CHALLENGES.find((c) => c.id === id)
}
